### ISSUE TITLE
Project Execution Images

### ISSUE THREAD

**Issue by MaksimoRamaj** [Ergys2002/rate-university-application-api#12]
![Screenshot_2](https://github.com/Ergys2002/rate-university-application-api/assets/133498622/6babb58d-28fe-45f1-8524-ff8c4fcbf3f1)
![Screenshot_2](https://github.com/Ergys2002/rate-university-application-api/assets/133498622/5e9b9f07-3ccb-499b-9846-23097fe0f71a)
![Screenshot_3](https://github.com/Ergys2002/rate-university-application-api/assets/133498622/175ad529-60a0-4c6b-94ab-eaddd663f65c)
![Screenshot_4](https://github.com/Ergys2002/rate-university-application-api/assets/133498622/b7889c52-4a1f-4dbc-83ec-63caa0842403)
![Screenshot_73](https://github.com/Ergys2002/rate-university-application-api/assets/133498622/c04e4408-720c-42ec-9324-555c80c078e0)
![Screenshot_1](https://github.com/Ergys2002/rate-university-application-api/assets/133498622/3c1694b6-3c2c-4a24-a7e7-e23641625b0c)

**Comment by Ergys2002** [comment]
![image](https://github.com/Ergys2002/rate-university-application-api/assets/125799161/df601636-e3f7-4a0b-99e5-6d597ea7ba21)
